language: scala

scala:
  - 2.11.8
  - 2.12.1

env:
  - JDK=oraclejdk8
  - JDK=oraclejdk7
  - JDK=openjdk6

before_script:
  - jdk_switcher use $JDK

matrix:
  exclude:
    - scala: 2.12.0 # skip java 6 for scala 2.12
      env: JDK=openjdk6
    - scala: 2.12.0 # skip java 7 for scala 2.12
      env: JDK=openjdk7
